### ISSUE TITLE
Define _variables in main.scss before anything else

### ISSUE THREAD

**Issue by httpsterio** [theomjones/fundamental#3]
I think it would make sense, as you can use the variables in the _fundamentals.scss if you move the variables up. I don't see how it could break anything, but it took me a solid 5 minutes to realise why my variables were broken (haven't configured source maps as this is my scss project yet :D)

**Comment by theomjones** [comment]
That file (probably badly named) isn't really meant to be touched, it's similar in intent to [Normalize](https://necolas.github.io/normalize.css/). Closing for now unless you think there's a good reason to go editing this file.
